---
title: "Someplots"
format: html
code-fold: true
code-tools: true
execute:
 message: false
 warning: false
---

```{r}
library(readr)
library(janitor)
library(tidyverse)
library(patchwork)
library(modelsummary)
# Load HousingPanelwide data
HousingPanelwide <- read_csv("d:/PositStuff/gmpanel/HousingPanelwide.csv")
par(mfrow=c(1,2))
ts.plot(cbind(log(HousingPanelwide$`kersal.Local Authority etc`),log(HousingPanelwide$`quays.Local Authority etc`)),col=c("darkgreen","red"),xlab="Census Wave",ylab="log(HousingTenure)",main="Local authority owned tenure 1971-2021 census")
  legend("bottomleft",legend = c("kersal_log(green)","quays_log(red)"),col=c("darkgreen","red"),bty = "n")

ts.plot(cbind(log(HousingPanelwide$`chettam.Local Authority etc`),log(HousingPanelwide$`ancoats.Local Authority etc`),log(HousingPanelwide$`crumpsall.Local Authority etc`)),col=c("darkgreen","red","darkblue"),xlab="Census Wave",ylab="log(HousingTenure)",main="Local authority owned tenure 1971-2021 census")
legend("bottomleft",legend = c("chettam_log(green)","ancoats_log(red)","crumpsall_log(blue)"),col=c("darkgreen","red","darkblue"),bty = "n")
```

```{r}
EducationPanelwide <- read_csv("d:/PositStuff/gmpanel/EducationPanelwide.csv")
par(mfrow=c(1,2))
ts.plot(cbind(EducationPanelwide$`kersal.Graduate`/(EducationPanelwide$kersal.Graduate+EducationPanelwide$`kersal.Not graduate`),EducationPanelwide$`quays.Graduate`/(EducationPanelwide$quays.Graduate+EducationPanelwide$`quays.Not graduate`)),col=c("darkgreen","red"),xlab="Census Wave",ylab="%Graduates",main="Graduate education 1971-2021 census")
  legend("topleft",legend = c("kersal(green)","quays(red)"),col=c("darkgreen","red"),bty = "n")

ts.plot(cbind(EducationPanelwide$`chettam.Graduate`/(EducationPanelwide$chettam.Graduate+EducationPanelwide$`chettam.Not graduate`),EducationPanelwide$`ancoats.Graduate`/(EducationPanelwide$ancoats.Graduate+EducationPanelwide$`ancoats.Not graduate`),EducationPanelwide$`crumpsall.Graduate`/(EducationPanelwide$crumpsall.Graduate+EducationPanelwide$`crumpsall.Not graduate`)),col=c("darkgreen","red","darkblue"),xlab="Census Wave",ylab="%Graduates",main="Graduate education 1971-2021 census")
legend("topleft",legend = c("chettam(green)","ancoats(red)","crumpsall(blue)"),col=c("darkgreen","red","darkblue"),bty = "n")
```


```{r}
EducationPanellong <- EducationPanelwide |>
  # Create a row identifier 
  mutate(row_id = row_number()) |>
  
  
  pivot_longer(
    cols = -c(1, row_id),
    names_to = c("location", "variable"),
    names_pattern = "^(.*?)\\.(.*)$" #No i do not know how to use pattern matching properly, had to look it up#
  ) |>
  
  # Pivot wider while respecting the row_id and location mapping
  pivot_wider(
    id_cols = c(row_id, location),
    names_from = variable,
    values_from = value
  ) |>
  
  # 4. Clean up the temporary row_id column
  select(-row_id) |>
    janitor::clean_names()
```


```{r}
HousingPanellong <- HousingPanelwide |>
  # 1. Create a row identifier so each year stays separate
  mutate(row_id = row_number()) |>
  
  pivot_longer(
    cols = -c(1, row_id),
    names_to = c("location", "variable"),
    names_pattern = "^(.*?)\\.(.*)$"
  ) |>
  
  pivot_wider(
    id_cols = c(row_id, location),
    names_from = variable,
    values_from = value
  ) |>
  
  select(-row_id) |>
  janitor::clean_names()
```


```{r}
PanelLong = merge(HousingPanellong,EducationPanellong) |>
  mutate(gentrified=ifelse(location%in%c("ancoats","quays"),1,0))

```


```{r}
p1=ggplot(PanelLong,aes(x=year,y=graduate/(graduate+not_graduate),colour=location))+geom_line()+ylab("%Graduates")+theme_light()
p2=ggplot(PanelLong,aes(x=year,y=graduate/(graduate+not_graduate),colour=factor(gentrified)))+stat_summary(fun=mean,geom="line")+geom_jitter()+ylab("%Graduates")+theme_dark()
p2/p1
p3=ggplot(PanelLong,aes(x=year,y=local_authority_etc/(owner_occupied+other_rented+other_tenures+local_authority_etc),colour=location))+geom_line()+ylab("%LocalAuthority")+theme_light()
p4=ggplot(PanelLong,aes(x=year,y=local_authority_etc/(owner_occupied+other_rented+other_tenures+local_authority_etc),colour=factor(gentrified)))+stat_summary(fun=mean,geom="line")+geom_jitter()+ylab("%LocalAuthority")+theme_dark()
p4/p3
p5=ggplot(PanelLong,aes(x=year,y=owner_occupied/(owner_occupied+other_rented+other_tenures+local_authority_etc),colour=location))+geom_line()+ylab("%Owner_occupied")+theme_light()
p6=ggplot(PanelLong,aes(x=year,y=owner_occupied/(owner_occupied+other_rented+other_tenures+local_authority_etc),colour=factor(gentrified)))+stat_summary(fun=mean,geom="line")+geom_jitter()+ylab("%Owner_occupied")+theme_dark()
p6/p5
p7=ggplot(PanelLong,aes(x=year,y=(other_rented+other_tenures)/(owner_occupied+other_rented+other_tenures+local_authority_etc),colour=location))+geom_line()+
  ylab("%other_rented+tenures")+theme_light()
p8=ggplot(PanelLong,aes(x=year,y=(other_rented+other_tenures)/(owner_occupied+other_rented+other_tenures+local_authority_etc),colour=factor(gentrified)))+
stat_summary(fun=mean,geom="line")+geom_jitter()+ylab("%other_rented+tenures")+theme_dark()
p8/p7
```

```{r}
combined_plot = (p4/p3)|(p6/p5)|(p8/p7) + plot_layout(guides = "collect")
modelsummary::datasummary_skim(PanelLong)
```

```{r}
EducationPanelProp = EducationPanellong |>
  mutate(GraduateP=graduate/(graduate+not_graduate),
  NGraduateP = not_graduate/(graduate+not_graduate))
  HousingPanelProp = HousingPanellong |>
    mutate(local_authority_etcP=local_authority_etc/(owner_occupied+local_authority_etc+other_rented+other_tenures),
   owner_occupiedP=owner_occupied/(owner_occupied+local_authority_etc+other_rented+other_tenures),
    otherrented_tenuresP=(other_rented+other_tenures)/(owner_occupied+local_authority_etc+other_rented+other_tenures))
    LongPanelProp = merge(EducationPanelProp,HousingPanelProp)
    LongPanelPropj= select(LongPanelProp,c(location,year,GraduateP,local_authority_etcP,owner_occupiedP, otherrented_tenuresP)) |>
  mutate(gentrified=ifelse(location%in%c("ancoats","quays"),1,0))
```

```{r}
#Simon Rudkin Didn't sponsor this I promise, i just found his posters very pretty and wanted to try and make some too#
library(BallMapper)
set.seed(123)
values = LongPanelPropj$GraduateP
points =  LongPanelPropj[,c(4,5,6)]
ball = BallMapper::BallMapper(as.data.frame(points),as.data.frame(values),epsilon = 0.01)
ball = BallMapper::BallMapper(as.data.frame(points),as.data.frame(values),epsilon = 0.17) #epsilon 0.17 seems to preserve the complexity in the best way
ballassign = ball$points_covered_by_landmarks
#Split by gentrificaiion#
Gentonly = filter(LongPanelPropj,gentrified==1)
values = Gentonly$GraduateP
points =  Gentonly[,c(4,5,6)]
ball1 = BallMapper::BallMapper(as.data.frame(points),as.data.frame(values),epsilon = 0.17) #epsilon 0.17 seems to preserve the complexity in the best way

Gentnot = filter(LongPanelPropj,gentrified==0)
values = Gentnot$GraduateP
points =  Gentnot[,c(4,5,6)]
ball2 = BallMapper::BallMapper(as.data.frame(points),as.data.frame(values),epsilon = 0.17) #epsilon 0.17 seems to preserve the complexity in the best way

ColorIgraphPlot(ball,showLegend = TRUE) + title("Ball Map of Gentrification e=0.17,(Grad%)")
ColorIgraphPlot(ball1,showLegend = TRUE) + title("Ball Map of Gentrifiying areas e=0.17,(Grad%)")
ColorIgraphPlot(ball2,showLegend = TRUE) + title("Ball Map of non gentrifying areas e=0.17,(Grad%)")
```


```{r}
#WARNING AI Generated Code as I am only learning how to properly add unit time labels to Ball Mapper Graphs#
library(igraph)
library(ggraph)
library(ggplot2)

# 1. Number of nodes
n_nodes <- length(ball$coloring)

# 2. Calculate ball sizes from your ballassign indices
ball_sizes <- sapply(ball$points_covered_by_landmarks, length)

# 3. Generate unit-time labels for each ball
node_labels <- sapply(ball$points_covered_by_landmarks, function(indices) {
  subset_data <- PanelLong[indices, ]
  paste0(subset_data$location, "-", subset_data$year, collapse = "\n")
})

# 4. Build the vertices data frame safely
vertices_df <- data.frame(
  name = 1:n_nodes,
  label = node_labels,
  coloring = ball$coloring,
  size = ball_sizes
)

# 5. Create the igraph object
g <- graph_from_data_frame(d = ball$edges, vertices = vertices_df, directed = FALSE)
#Though I did customise the plot below though#
ggraph(g, layout = "stress") +
  geom_edge_link(alpha = 0.8, color = "gray60") +
  geom_node_point(aes(size = size, color = coloring)) +
  geom_node_text(aes(label = label), repel = TRUE, size = 2.5, color = "black") +
  scale_color_viridis_c() +
  theme_light() +
  labs(title = "Ball Mapper Graph of gentrification - points in the same ball are closest on housing market makeup withing +-17 percentage points",
       color = "%Graduates", size = "Ball Size(number of points)") + scale_size_continuous(range = c(2, 5))
datasummary_skim(LongPanelPropj)      
```

```{r}
#My idea is to now  augment the code to create separate plots for gentrified and non gentrified areas
n_nodes <- length(ball1$coloring)

# 2. Calculate ball sizes from your ballassign indices
ball_sizes <- sapply(ball1$points_covered_by_landmarks, length)

# 3. Generate unit-time labels for each ball
node_labels <- sapply(ball1$points_covered_by_landmarks, function(indices) {
  subset_data <- Gentonly[indices, ]
  paste0(subset_data$location, "-", subset_data$year, collapse = "\n")
})

# 4. Build the vertices data frame safely
vertices_df <- data.frame(
  name = 1:n_nodes,
  label = node_labels,
  coloring = ball1$coloring,
  size = ball_sizes
)

# 5. Create the igraph object
g <- graph_from_data_frame(d = ball1$edges, vertices = vertices_df, directed = FALSE)
#Though I did customise the plot below though#
 g1 = ggraph(g, layout = "stress") +
  geom_edge_link(alpha = 0.8, color = "gray60") +
  geom_node_point(aes(size = size, color = coloring)) +
  geom_node_text(aes(label = label), repel = TRUE, size = 6, color = "black") +
  scale_color_viridis_c() +
  theme_light() +
  labs(title = "Ball Mapper Graph of gentrified areas - points in the same ball are closest on housing market makeup withing +-17 percentage points",
       color = "%Graduates", size = "Ball Size(number of points)") + scale_size_continuous(range = c(4, 10))
```

```{r}

n_nodes <- length(ball2$coloring)

# 2. Calculate ball sizes from your ballassign indices
ball_sizes <- sapply(ball2$points_covered_by_landmarks, length)

# 3. Generate unit-time labels for each ball
node_labels <- sapply(ball2$points_covered_by_landmarks, function(indices) {
  subset_data <- Gentnot[indices, ]
  paste0(subset_data$location, "-", subset_data$year, collapse = "\n")
})

# 4. Build the vertices data frame safely
vertices_df <- data.frame(
  name = 1:n_nodes,
  label = node_labels,
  coloring = ball2$coloring,
  size = ball_sizes
)

# 5. Create the igraph object
g <- graph_from_data_frame(d = ball2$edges, vertices = vertices_df, directed = FALSE)
#Though I did customise the plot below though#
g0 = ggraph(g, layout = "stress") +
  geom_edge_link(alpha = 0.8, color = "gray60") +
  geom_node_point(aes(size = size, color = coloring)) +
  geom_node_text(aes(label = label), repel = TRUE, size = 4, color = "black") +
  scale_color_viridis_c() +
  theme_light() +
  labs(title = "Ball Mapper Graph of non gentrified areas - points in the same ball are closest on housing market makeup withing +-17 percentage points",
       color = "%Graduates", size = "Ball Size(number of points)") + scale_size_continuous(range = c(4, 10))
 g1/g0      

```